#!/bin/bash
###############################################################################################
#                                                                                             #
#   Installation of Translation tools                                                         #
#                                                                                             #
#   curl -s https://raw.githubusercontent.com/vertelab/odoosa-translate/master/install | bash #
#                                                                                             #
###############################################################################################

curl -s https://raw.githubusercontent.com/vertelab/odoosa-translate/refs/heads/main/requirements.txt | sudo -H pip3 install --break-system-packages -r /dev/stdin

sudo curl -L -o /usr/local/bin/odoopopull https://raw.githubusercontent.com/vertelab/odoosa-translate/refs/heads/main/odoopopull.py
sudo chown root:root /usr/local/bin/odoopopull
sudo chmod +x /usr/local/bin/odoopopull

sudo curl -L -o /usr/local/bin/odoopodiff https://raw.githubusercontent.com/vertelab/odoosa-translate/refs/heads/main/odoopodiff.py
sudo chown root:root /usr/local/bin/odoopodiff
sudo chmod +x /usr/local/bin/odoopodiff

## dev alternative
sudo curl -L -o /usr/local/bin/odoopodiff2 https://raw.githubusercontent.com/vertelab/odoosa-translate/refs/heads/main/odoopodiff2
sudo chown root:root /usr/local/bin/odoopodiff2
sudo chmod +x /usr/local/bin/odoopodiff2

# sv.poline 3, after the star * is <module> name | check all modules from every distributor as we use
sudo curl -L -o /usr/local/bin/check_module_name_in_po_file https://raw.githubusercontent.com/vertelab/odoosa-translate/refs/heads/main/check_module_name_in_po_file.py
sudo chown root:root /usr/local/bin/check_module_name_in_po_file
sudo chmod +x /usr/local/bin/check_module_name_in_po_file.py
